### ISSUE TITLE
Feature Request: Inverting/Blending PDF 

### ISSUE THREAD

**Issue by bwoah-md** [ElsaTam/obsidian-fancy-a-story#1]
I wanted to have a PDF inverting in Dark Mode and PDF blending in Light Mode options... It'd be great to enable this through style settings maybe?

**Comment by ElsaTam** [comment]
Thanks for the suggestion! I've added it, it will be pushed in the next release :)

**Comment by ElsaTam** [comment]
It should be added the next time you update the theme.
Here is the documentation: https://elsatam.github.io/obsidian-fancy-a-story/docs/stylesettings/stylesettings.html#pdfs
I'm closing this issue, but if you have any other adjustment needed, reopen it :)
