### ISSUE TITLE
Theme causes blank screen

### ISSUE THREAD

**Issue by IntegralGuide** [ElsaTam/obsidian-fancy-a-story#11]
With the theme installed, if I switch between reading and editing mode a time or two, the entire window goes blank. I have to go into the .obsidian folder and change the theme manually to use Obsidian again.

This happens with no plugins or snippets active.

**Comment by ElsaTam** [comment]
Hi @IntegralGuide . Sorry for the inconvenience.
Can you check your Installer version of Obsidian? Not the Current version, but what is just under it. It has to be 1.6.5 minimum.

![](https://github.com/ElsaTam/obsidian-fancy-a-story/blob/main/screenshots/installer_version.png?raw=true)

**Comment by ElsaTam** [comment]
No worries! Have fun with it :)
