### ISSUE TITLE
Suggestion:a setting to display images in the center.

### ISSUE THREAD

**Issue by AlfredWoods** [ElsaTam/obsidian-fancy-a-story#15]
Is it possible to add a setting in the theme to display images in the center by default?

**Comment by ElsaTam** [comment]
Sure thing! I will add that in the next release and ping you here once it's available :)

**Comment by ElsaTam** [comment]
@AlfredWoods You can now update and then find the setting in Style Settings > Fancy-a-Story > Editor > Images > Center images

It will center images that are not part of a paragraph.
```markdown
The following image will not be centered
![[image1.png]]

But this second one will

![[image2.png]]
```

In live preview, the only images that will be centered are the internal ones and if images in the vault have no striped shadows.
In reading mode, it should work fine for every image.

**Comment by AlfredWoods** [comment]
@ElsaTam The feature is no effect in Simplified Chinese.

**Comment by ElsaTam** [comment]
@AlfredWoods What do you mean? Can you send a screenshot? I don't see why the displayed text would have anything to do with the centering of images.

**Comment by AlfredWoods** [comment]
@ElsaTam

**Comment by ElsaTam** [comment]
Thanks for the screenshots . Make sure you are in reading mode, not in editing mode. And make sure you have an empty line after the image as well. The image must be isolated from the rest of the text

**Comment by AlfredWoods** [comment]
@ElsaTam Thanks! I tried this feature and it's awesome!

**Comment by ElsaTam** [comment]
Glad that it's working!
