### ISSUE TITLE
"File Explorer Decorator Blending Mode" not working on Mobile

### ISSUE THREAD

**Issue by bwoah-md** [ElsaTam/obsidian-fancy-a-story#2]
![Screenshot_2024-10-18-18-40-35-04_51606159b24eff83e24a54116878fe3e.jpg](https://github.com/user-attachments/assets/ea057829-6563-4f08-8ee5-cd087b5508f4)

![Screenshot_2024-10-18-18-40-54-00_51606159b24eff83e24a54116878fe3e.jpg](https://github.com/user-attachments/assets/eea6a0df-3a3c-494b-9cde-64fdddf1d5d3)

**Comment by ElsaTam** [comment]
Thanks! It will be fixed in the next release :)

**Comment by ElsaTam** [comment]
It should be fixed.
