### ISSUE TITLE
Bold Emphasizing isn't Working with any Mono Fonts (e.g. Jetbrains Mono, SF Pro, DM Mono)

### ISSUE THREAD

**Issue by bwoah-md** [ElsaTam/obsidian-fancy-a-story#5]
![image](https://github.com/user-attachments/assets/89607206-1568-4493-aa40-c2a9868f6fa9)

> *Tested in restricted mode and by disabling all CSS snippets*

### Remark
- The text isn't being emphasized (as a bold text) whenever I am using any MONO fonts ...

- [x] Italicizing text is working 

![image](https://github.com/user-attachments/assets/ec799ecf-30c6-4aee-961d-676deb8ee8ea)

**Comment by ElsaTam** [comment]
It might be the font you are using. I don't see why my theme would do anything like that, right now.
If you use the Default theme, does the text shows up bold with the same font?

**Comment by bwoah-md** [comment]
yeah it does, i'll check with a whole new vault then

**Comment by bwoah-md** [comment]
it works with the other fonts but not with mono ones, I think this could be a problem on my side but I am not sure

**Comment by ElsaTam** [comment]
It might be because the mono font you are using does not have a bold variant, only regular weight. If you can't have a bold text in a new vault with nothing installed, then it's indeed a font issue :)

**Comment by ElsaTam** [comment]
Should be fixed in version 1.0.8 (in case it was not the font causing the issue)
